### ISSUE TITLE
Archlinux上使用DDE多窗口同时打开出现黑底

### ISSUE THREAD

**Issue by chenweihao1006** [linuxdeepin/dde-kwin#120]
在Archlinux平台上安装DDE多窗口打开，非当前窗口会出现大黑底（比窗口大一圈的黑色）
不确定是否应该提交到这里
（有N卡，没装闭源驱动）

**Comment by chenweihao1006** [comment]
此为偶发现象，重启之后就暂时不出现，过一段时间后再次出现

**Comment by xmuli** [comment]
此属于已已知问题，Archlinux + DDE 专有，是 dde-kwin 的锅，出现一次大黑边，就杀一次 `killall kwin_x11` , 与  [# 115](https://github.com/linuxdeepin/dde-kwin/issues/115) 重复，故关闭
