### ISSUE TITLE
Multitasking view not working in arch linux after DDE install

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [linuxdeepin/dde-kwin#124]
### Environment

OS: Arch Linux
Kernel Version: 5.8.12-arch-1-1
Deepin Version: 20 Beta
Deepin-kwin version:  5.2.0.2-2
Window Effects are on in personalization settings.

### User Action
I pressed the multitasking view button when multiple applications were open on the screen.

### Expected Result
The multitaking view should have opened up which shows open applications and desktops

### Actual Result
Nothing happened. No alerts were shown either even after multiple tries

**Comment by xmuli** [comment]
This feature has always been disabled on Arch (a duplicate issue already)

**Comment by L04DB4L4NC3R** [comment]
Okay, thank you
