### ISSUE TITLE
Glitch after opening the multitasking windows

### ISSUE THREAD

**Issue by anantamishra** [linuxdeepin/dde-kwin#125]
A glitch on inactive window of a application appears after opening the multitasking windows.
Screenshot attached below.

![image](https://user-images.githubusercontent.com/49669106/95382573-8d01e780-0909-11eb-9d63-3b05ef90704c.png)

**Comment by xmuli** [comment]
Looks a bit like the big black edge (already known) problem

**Comment by anantamishra** [comment]
abit same, its all due to incompability of kwnin

**Comment by xmuli** [comment]
Repeat, Close, for new replies see

[#115](https://github.com/linuxdeepin/dde-kwin/issues/115)
