### ISSUE TITLE
Doesn't compile with Kwin 5.21

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/dde-kwin#136]
Many this kind of errors: Doesn't compile with error: 
virtual void MultitaskingEffect::prePaintScreen(KWin::ScreenPrePaintData&, int)' marked 'override', but does not override

[build.log](https://github.com/linuxdeepin/dde-kwin/files/6029273/build.log)

**Comment by felixonmars** [comment]
Related: https://github.com/linuxdeepin/deepin-kwin/issues/47
