### ISSUE TITLE
archlinux源中的kwin升级之后dde无法打开特效模式

### ISSUE THREAD

**Issue by wecli** [linuxdeepin/dde-kwin#153]
系统：arch+dde
版本：kwin：5.22.2.1-1；dde-kwin：5.3.9-1对应deepin版本：5.3.9
操作：控制中心中切换dde桌面的特效模式或者使用快捷键win+shift+tab切换特效模式
预期：开启特效桌面
结果：
1、在控制中心开启特效模式的开关，按钮会打开然后很快关闭之后再点击无反应。
2、使用快捷开启特效模式提示无法开启特效模式，多次尝试之后会弹出窗口让用户选择窗口管理器。
主管看法：arch源中的kwin版本与dde-kwin包不兼容，arch维护的kwin相对deepin/uos版本更新更快，很容易出现与dde桌面不兼容的情况。希望官方可以考虑一下dde-kwin包的release tag的策略

**Comment by felixonmars** [comment]
请升级到 deepin-kwin 5.3.9-2 重试。

**Comment by wecli** [comment]
> 请升级到 deepin-kwin 5.3.9-2 重试。
谢谢大佬。
